M48
; DRILL file {KiCad (7.0.0)} date Thu Jun  8 15:27:55 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-08T15:27:55+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X6.7912Y-3.75
X7.0188Y-3.75
T2
X7.2411Y-3.85
X7.5089Y-3.85
T0
M30
